version: '3'

services:
  backend:
    image: kwong526/demo4640:latest     # ADJUST WITH YOUR IMAGE NAME
    depends_on:
      - database
    env_file:
      - variables.env
  database:
    image: mysql
    env_file:
      - variables.env
  web:
    build: web
    depends_on:
      - backend
    env_file:
      - variables.env
    ports:
      - 8000:80